### ISSUE TITLE
Expose Spotify normalization option

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_spotify#12]

**Comment by trbn1** [comment]
Would it be possible to expose this as a track ReplayGain value, or perhaps somehow setting the track RG value to 0dB and still keeping the normalization working correctly? Right now I have a RG preamp setting at -8dB for tracks without RG info, so all tracks now play way quieter than they should. What do you think about this?

**Comment by TheQwertiest** [comment]
> Would it be possible to expose this as a track ReplayGain value

Spotify API does not provide such information, so, sadly, no.

> or perhaps somehow setting the track RG value to 0dB

Can't to that, since that would be most likely not really true (and I don't want to provide wrong information): we don't have any information about Spotify's normalization algorithm, hence we can't make any assumptions on their target db value.
