### ISSUE TITLE
Provide %codec% metadata field

### ISSUE THREAD

**Issue by mstevens83** [TheQwertiest/foo_spotify#14]
For title formatting geekery it would be nice if your component would provide a value for the %codec% metadata field.

I'm not sure whether your component actually decodes the compressed audio stream. Perhaps libspotify handles that so your code might not be able to tell which codec was used. But in that case you can do a sensible guess: Spotify themselves mention Ogg/Vorbis is the format used at the bitrates your components ports (96, 160, 320kbps).
See: https://artists.spotify.com/faq/mastering-and-loudness#how-does-spotify-process-my-audio-files

As Ogg is just the container the correct %codec% value would thus be "Vorbis".

**Comment by TheQwertiest** [comment]
Implemented
