### ISSUE TITLE
Can't import playlists with local tracks

### ISSUE THREAD

**Issue by mist475** [TheQwertiest/foo_spotify#16]
When you try to import a playlist with a local track you get the following error:

> The following error(s) occurred during loading of the location(s):
> [json.exception.type_error.302] type must be string, but is null

**Comment by TheQwertiest** [comment]
I could not reproduce the error with my private playlists, so this is probably something specific to the items in your playlist.
- Could you make your playlist public temporarily, so I could access and test it? (you can PM me on Hydrogen forums, if you are not comfortable publishing the link here).
- Alternatively you can extract JSON manually:
  - Go to <https://developer.spotify.com/console/get-playlist-tracks/?limit=100>
  - Paste your playlist id.
  - Get the auth token (don't forget to tick `playlist-read-private`)
  - Click `Try it`.
  - You can post the resulting JSON here or send it via PM on Hydrogen.

**Comment by mist475** [comment]
If think i figured out the problem, all of the playlists i tested had at least one local track.

**Comment by TheQwertiest** [comment]
Supporting `local` Spotify tracks is rather tricky, and TBH I don't see much reason to do so, since foobar2000 already has built-in `local` track playback functionality =)
What I will do, however, is filter out such tracks when parsing the playlist.

**Comment by TheQwertiest** [comment]
Local track filter is implemented, so now you should be able to at least import such playlists.

**Comment by mist475** [comment]
I Just tested the issue, it still persists.
test [playlist:](https://open.spotify.com/playlist/4GixLiT2Xdzs8ljEH8pa8a?si=PO2vpnwrQCGEwP66fbePRw)

**Comment by TheQwertiest** [comment]
Should be fixed in the latest nightly
