### ISSUE TITLE
Multi-value tags are not displayed correctly

### ISSUE THREAD

**Issue by mist475** [TheQwertiest/foo_spotify#17]
When i play a song by multiple artists, instead of foobar displaying all artists, the original artist name is displayed the amount of times there are artists. For instance, the image below should contain the artists 'Rob Scallon' & 'Pete Cottrell'
![issueSpotify](https://user-images.githubusercontent.com/70655895/95761012-043dcf80-0cac-11eb-9751-39dbccc7c656.PNG)

**Comment by TheQwertiest** [comment]
Ah, I see you're a man of culture as well =)

**Comment by TheQwertiest** [comment]
Should be fixed now.
