### ISSUE TITLE
Crash: Illegal operation

### ISSUE THREAD

**Issue by mist475** [TheQwertiest/foo_spotify#19]
Every now and then foobar crashes while using this plugin. My theme also crashes every now and again, though i suspect that to be a different issue. Crashes happen seemingly random while skipping tracks.
[failure_00000006.txt](https://github.com/TheQwertiest/foo_spotify/files/5376355/failure_00000006.txt)

**Comment by TheQwertiest** [comment]
Can you attach the crash dump as well? Since I can't diagnose the issue without it.

**Comment by mist475** [comment]
[failure_00000006.zip](https://github.com/TheQwertiest/foo_spotify/files/5376610/failure_00000006.zip)
Sure

**Comment by TheQwertiest** [comment]
Should be fixed now.
