### ISSUE TITLE
Album Art doesn't refresh with specific theme

### ISSUE THREAD

**Issue by mist475** [TheQwertiest/foo_spotify#26]
(Issue was present before the 429 issue)
When i play a playlist using Georgia the album artwork doesn't update. i'm not sure if this is an issue with the plugin or with the theme. When you skip a track the album art does update, when you let tracks finish it doesn't. When you refresh the theme it does show the artwork just fine.

**Comment by TheQwertiest** [comment]
Can't test this, because of 429. Currently all requests end up with 429. Non-cached album art fetching being one of them.

**Comment by mist475** [comment]
Yeah, i just put it up before i forgot about it again. Good luck dealing with the 429 issue.

**Comment by mist475** [comment]
I just tested it further with a few cached songs, the issue only persists with spotify tracks, spotify tracks into non- spotify tracks and vice-versa work fine.

**Comment by mist475** [comment]
Just discovered the same issue exists with foo_youtube meaning that this is an issue with the theme, not with the plugin.
