### ISSUE TITLE
Extra silence at the end of track

### ISSUE THREAD

**Issue by mstevens83** [TheQwertiest/foo_spotify#33]
When playing a "mixed" album I can hear clear gaps between the tracks. The transition is smooth when listening with Spotify's own client.
Example content: https://open.spotify.com/album/43usrhesfR3koh4FVWPyWz?si=21_fu2eDQESLD3Vm6IObQA

**Comment by TheQwertiest** [comment]
I've investigated this a bit and it seems that Spotify adds zero-filled frames at the end of the song :\\
Official client uses a different method of music delivery, which might be preventing such problems.

**Comment by mstevens83** [comment]
Is there any way to detect and skip the gap?

**Comment by TheQwertiest** [comment]
Should be fixed in the nightly build

**Comment by mstevens83** [comment]
Works like a charm! Thanks!
