### ISSUE TITLE
librespot integration

### ISSUE THREAD

**Issue by jscholes** [TheQwertiest/foo_spotify#39]
Just discovered this plug-in today; great work!  I wondered, with the likely demise of libspotify at some point, along with its limited functionality, if you'd considered integrating [librespot](https://github.com/librespot-org/librespot) instead?  It would open up several avenues including zeroconf-based authentication, Spotify Connect, radio/"smart" playlists, etc.

**Comment by TheQwertiest** [comment]
The likelihood of this is (currently) close to zero:
- librespot does not work properly on Windows.
- There is no way to build librespot as a dll with C/C++ interface, so it can't be consumed easily by this component. And I have zero interest in learning Rust =)

**Comment by jscholes** [comment]
Thanks for taking the time to provide your reasoning.  Makes total sense and I appreciate the response.
