### ISSUE TITLE
Premium account for libspotify?

### ISSUE THREAD

**Issue by diallobakary4** [TheQwertiest/foo_spotify#40]
Could please confirm that a premium account is required for LibSpotify.
If that is the case, meaning that I can't playback from Spotify?
I could loggin in WebAPI.
![image](https://user-images.githubusercontent.com/13533717/99359571-f5a09480-28b7-11eb-9f06-5d0aee47fc2d.png)

**Comment by TheQwertiest** [comment]
Premium account is required as per [Install prerequisites](https://theqwertiest.github.io/foo_spotify/docs/installation/#prerequisites).
