### ISSUE TITLE
Any possible way to download a playlist?

### ISSUE THREAD

**Issue by Bkamahl** [TheQwertiest/foo_spotify#44]
Is there any possible way or plans to be able to download songs like we can via the Spotify app? I doubt it seeing how stingy Spotify seems to be. Sorry if this isnt the right place for this either, but I'd rather the song be looked up from storage rather then redownloaded from the internet.

**Comment by TheQwertiest** [comment]
`foo_spotify` caches all the downloaded songs (cache size is configurable in component's preferences). Hence, it won't download the track if it was already played.

If you mean "download tracks as .mp3", then no, ripping music is not a purpose of this component and it won't ever be supported.

**Comment by Bkamahl** [comment]
Ah okay, no I don't mean ripping it :) , glad to know I wont constantly be redownloading the songs though.
