### ISSUE TITLE
Support for podcasts and radio

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_spotify#45]
Podcasts and radio can't be supported, because they are not accessible with the currently available Spotify public API (i.e. libspotify)

**Comment by DeathWrench** [comment]
Taken from this thread: https://hydrogenaud.io/index.php?PHPSESSID=nbrhjf579a0gkb38j4mibian00&topic=119972.100

Don't know how long this will last but adding the following to the host file fixed for me.

```
# apresolve.spotify.com has replaced ap.gslb.spotify.com, but the libspotify has
# the FQDN hard-coded; hence this attempt to alias "ap" to one of the host listed
# from apresolve
35.190.242.176     ap.gslb.spotify.com # gew1-accesspoint-a-dfff.ap.spotify.com
```
