### ISSUE TITLE
Link spotify playlist to "convert" module

### ISSUE THREAD

**Issue by aquascop** [TheQwertiest/foo_spotify#46]
Currently the convert module is not accessible with a playlist opened with foo_spotify : 
"
Source: "spotify:track:...."
  Unable to open source file: Access denied
  Conversion failed: Access denied
"
any idea to make it possible ?
thanks
Laurent

**Comment by TheQwertiest** [comment]
See the answer here: https://hydrogenaud.io/index.php?topic=119972.msg988788#msg988788

**Comment by aquascop** [comment]
ok, thanks for the answer, i understand the choice
