### ISSUE TITLE
Spotify tracks/playlists can't be added or played

### ISSUE THREAD

**Issue by segrived** [TheQwertiest/foo_spotify#47]
Today when i try to load playlist to fb2k, only single invalid entry is added to player.
For example for URL https://open.spotify.com/playlist/2UmSkliK7pZzohnDjtbo9k i gets only this:
![image](https://user-images.githubusercontent.com/1504181/108275316-d8ad8300-717e-11eb-8dfd-e085689d52e7.png)

Same behavior when i try to add single track. Yesterday everything works fine, like previous months.

**Comment by TheQwertiest** [comment]
Yup, confirmed. Will try to rollout the fix later today.
