### ISSUE TITLE
URL import broken

### ISSUE THREAD

**Issue by ReallyAnotherUser** [TheQwertiest/foo_spotify#58]
Since a few hours/days i cannot import URL's into foobar anymore. Playback of already imported songs still works. I did not change anything on my Spotify Account or in Foobar. Is this Spotify dropping support? Can there still be something done (since playback still works)?
Im getting this error:

The following error(s) occurred during loading of the location(s):
Not Acceptable (406)

**Comment by instinctualjealousy** [comment]
Can confirm. The albums I stored in M-TAGS files (for library usage) still work. It's the same error as well.

**Comment by deckard1965** [comment]
Me too! I can't paste any Spotify URL !!
Would you confirm this error?

**Comment by itsViktorRyan** [comment]
I was wondering why I was having issues importing an update to a playlist I made this evening. I tried to check to see if there were any conflicting issues with other components but to no avail unfortunately

**Comment by parktheredcar** [comment]
It seems like they're rejecting the `foobar2000/1.6.2` user agent. You can work around this by configuring foobar to use a proxy, and setting the proxy to replace the User-Agent header on each request.

For example with mitmproxy, create useragent.text in your home dir containing a recent chrome user agent, and run this way.
`mitmproxy --modify-headers /~q/User-Agent/@~/useragent.txt`
Then under network settings configure foobar to use localhost:8080 and in advanced network settings disable certificate https checking for open.spotify.com

**Comment by itsViktorRyan** [comment]
So I checked once again just to see if the issue would resolve on its own, and apparently I was able to get it to reimport without needing to do anything else, so it may possibly be fixed?

**Comment by deckard1965** [comment]
I also checked again, so nothing happend !! I wonder why URL import-error occured yesterday.

**Comment by ReallyAnotherUser** [comment]
Seems to work again smh
