### ISSUE TITLE
Sunsetting of LibSpotify

### ISSUE THREAD

**Issue by AsagiK** [TheQwertiest/foo_spotify#65]
Any plans of migrating the component to Web Playback SDK now that LibSpotify is gone?

**Comment by paulb39** [comment]
I love this plugin and really hope they can get it to work. But I must be missing something because as far as can tell Web Playback SDK works with javascript, and I can't find any wrappers for it.

**Comment by TheQwertiest** [comment]
Web Playback can only be used in browsers. And I don't thinks it's possible to integrate browser playback properly in fb2k, since such playback is encapsulated in browser and can't be transformed to raw data that is needed by fb2k.

Also see #68
