### ISSUE TITLE
Playback API deprecation

### ISSUE THREAD

**Issue by TheQwertiest** [TheQwertiest/foo_spotify#68]
Spotify deprecated the library that was used to implement playback in this component ([Link](https://developer.spotify.com/community/news/2022/04/12/libspotify-sunset/)).
There are no viable Windows alternatives that could be used to replace it, hence this project is suspended until such alternative appears.

**Comment by deckard1965** [comment]
So sad....
Is there any chance to find alrernative plan ?

**Comment by instinctualjealousy** [comment]
To interested developers (not me):
librespot has been made to work on Windows in the ncspot client, but it's a CLI ncurses client that probably isn't to the desire of most foobar users.

One of the librespot library's available output devices is an stdout pipe- maybe something can be done with this to get the PCM feed directly into foobar? foobar wouldn't be doing all the decoding, sadly, but it'd be doing enough to be compliant with the playback engine and effects, as it'd be raw PCM for foobar to decode. You won't see the true bitrate or the true codec this way, but it might be possible for librespot to communicate that information to extra fields in the foobar file properties.

This isn't getting into the "can you build this into a foobar plugin" territory though, might require significant changes to librespot itself (like porting it to C/C++, even) to make work in this context. Just brainstorming. I know nothing.

I don't know how its feature parity is, but there's also a Java version of librespot if for some reason it'd be easier to work with that build.
