### ISSUE TITLE
LibSpotify login error "Needs Premium Account" when I have Premium for Family active

### ISSUE THREAD

**Issue by Nukael** [TheQwertiest/foo_spotify#69]
Installed [foobar2000 v1.6.11], downloaded v1.1.3 - Hotfix.
WebAPI is working and I can open a playlist, but when I want to start playing it requires to log in. Probably the LibSpotify.
And it responds with an error "Needs Premium Account" when I have Premium for Family active.

**Comment by MiliAxe** [comment]
Unfortunately, Spotify has decided to deprecate their Libspotify library that is used in this plugin and as stated in the repository's readme file, this plugin doesn't until a solution is found for it (which is quite unlikely).
Take a look at #68 for more information.

**Comment by TheQwertiest** [comment]
https://github.com/TheQwertiest/foo_spotify/issues/68
